name: publish openapi ui

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: version to be published
        required: false
        type: string

jobs:
  publish:
    uses: eclipse-edc/.github/.github/workflows/publish-openapi-ui.yml@main
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}
